export default [
    "// In this file, you can add hostnames to be redirected.",
    "dynadot.com",
    "porkbun.com",
    "godaddy.com",
    "register.com",
    "namecheap.com",
    "iwantmyname.com",
    "enom.com",
    "ovhcloud.com",
    "ionos.com",
    "ionos.co.uk",
    "123-reg.com",
    "123-reg.co.uk",
    "names.co.uk",
    "domain.com",
    "sedo.com",
    "dan.com",
    "domains.google",
    "afternic.com",
    "godaddy.co.uk",
    "hostinger.com",
    "hostinger.co.uk",
    "20i.com"
]